// <auto-generated />
using System;
using MAVN.Service.CustomerManagement.MsSqlRepositories.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MAVN.Service.CustomerManagement.MsSqlRepositories.Migrations
{
    [DbContext(typeof(CmContext))]
    [Migration("20191007083546_RemoveIsVerifiedFromPhoneVerificationCodeEntity")]
    partial class RemoveIsVerifiedFromPhoneVerificationCodeEntity
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("customer_management")
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Lykke.Service.CustomerManagement.MsSqlRepositories.Entities.CustomerFlagsEntity", b =>
                {
                    b.Property<string>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("customer_id");

                    b.Property<bool>("IsBlocked")
                        .HasColumnName("is_blocked");

                    b.HasKey("CustomerId");

                    b.ToTable("customer_flags");
                });

            modelBuilder.Entity("Lykke.Service.CustomerManagement.MsSqlRepositories.Entities.CustomerRegistrationReferralDataEntity", b =>
                {
                    b.Property<string>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("customer_id");

                    b.Property<string>("ReferralCode")
                        .IsRequired()
                        .HasColumnName("referral_code");

                    b.HasKey("CustomerId");

                    b.ToTable("customers_registration_referral_data");
                });

            modelBuilder.Entity("Lykke.Service.CustomerManagement.MsSqlRepositories.Entities.EmailVerificationCodeEntity", b =>
                {
                    b.Property<string>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("customer_id");

                    b.Property<DateTime>("ExpireDate")
                        .HasColumnName("expire_date");

                    b.Property<bool>("IsVerified")
                        .HasColumnName("is_verified");

                    b.Property<string>("VerificationCode")
                        .IsRequired()
                        .HasColumnName("code");

                    b.HasKey("CustomerId");

                    b.HasIndex("VerificationCode")
                        .IsUnique();

                    b.ToTable("email_verification_codes");
                });

            modelBuilder.Entity("Lykke.Service.CustomerManagement.MsSqlRepositories.Entities.PhoneVerificationCodeEntity", b =>
                {
                    b.Property<string>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("customer_id");

                    b.Property<DateTime>("ExpireDate")
                        .HasColumnName("expire_date");

                    b.Property<string>("VerificationCode")
                        .IsRequired()
                        .HasColumnName("code");

                    b.HasKey("CustomerId");

                    b.HasIndex("CustomerId", "VerificationCode")
                        .IsUnique();

                    b.ToTable("phone_verification_codes");
                });
#pragma warning restore 612, 618
        }
    }
}
