// <auto-generated />
using System;
using Lykke.Service.CustomerManagement.MsSqlRepositories.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Lykke.Service.CustomerManagement.MsSqlRepositories.Migrations
{
    [DbContext(typeof(CmContext))]
    [Migration("20190610091228_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("customer_management")
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Lykke.Service.CustomerManagement.MsSqlRepositories.Entities.VerificationCodeEntity", b =>
                {
                    b.Property<string>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("customer_id");

                    b.Property<DateTime>("ExpireDate")
                        .HasColumnName("expire_date");

                    b.Property<bool>("IsVerified")
                        .HasColumnName("is_verified");

                    b.Property<string>("VerificationCode")
                        .HasColumnName("code");

                    b.HasKey("CustomerId");

                    b.HasIndex("VerificationCode")
                        .IsUnique()
                        .HasFilter("[code] IS NOT NULL");

                    b.ToTable("verification_codes");
                });
#pragma warning restore 612, 618
        }
    }
}
